name: exploration_planner
description: The only app you'll need for exploring space.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_fonts: ^2.1.0
  flutter:
    sdk: flutter
  googleapis: ^7.0.0
  google_sign_in: ^5.2.1
  image_picker: ^0.8.5
  shared_preferences: ^2.0.13
  permission_handler: ^9.2.0
  sqflite: ^2.0.2
  flutter_share: ^2.0.0
  path_provider: ^2.0.3
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  syncfusion_flutter_xlsio: ^20.1.47-beta.1
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "lib/assets/Logo_slang_squarefondo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
